#############################################################################
# Makefile for building: luckygps
# Generated by qmake (2.01a) (Qt 4.7.3) on: So 7. Aug 14:33:52 2011
# Project:  luckygps.pro
# Template: subdirs
# Command: e:\Qt\qt-4.7.3\bin\qmake.exe -o Makefile luckygps.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = e:\Qt\qt-4.7.3\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-routing-plugins-client_plugins-pro \
		sub-routing-plugins-preprocessor_plugins-pro \
		sub-luckygps-client-pro

routing\plugins\$(MAKEFILE).client_plugins: 
	@$(CHK_DIR_EXISTS) routing\plugins\ $(MKDIR) routing\plugins\ 
	cd routing\plugins\ && $(QMAKE) e:\svn\luckygps\routing\plugins\client_plugins.pro -o $(MAKEFILE).client_plugins
sub-routing-plugins-client_plugins-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) routing\plugins\ $(MKDIR) routing\plugins\ 
	cd routing\plugins\ && $(QMAKE) e:\svn\luckygps\routing\plugins\client_plugins.pro -o $(MAKEFILE).client_plugins
sub-routing-plugins-client_plugins-pro: routing\plugins\$(MAKEFILE).client_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).client_plugins
sub-routing-plugins-client_plugins-pro-make_default-ordered: routing\plugins\$(MAKEFILE).client_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).client_plugins 
sub-routing-plugins-client_plugins-pro-make_default: routing\plugins\$(MAKEFILE).client_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).client_plugins 
sub-routing-plugins-client_plugins-pro-make_first-ordered: routing\plugins\$(MAKEFILE).client_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).client_plugins first
sub-routing-plugins-client_plugins-pro-make_first: routing\plugins\$(MAKEFILE).client_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).client_plugins first
sub-routing-plugins-client_plugins-pro-all-ordered: routing\plugins\$(MAKEFILE).client_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).client_plugins all
sub-routing-plugins-client_plugins-pro-all: routing\plugins\$(MAKEFILE).client_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).client_plugins all
sub-routing-plugins-client_plugins-pro-clean-ordered: routing\plugins\$(MAKEFILE).client_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).client_plugins clean
sub-routing-plugins-client_plugins-pro-clean: routing\plugins\$(MAKEFILE).client_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).client_plugins clean
sub-routing-plugins-client_plugins-pro-distclean-ordered: routing\plugins\$(MAKEFILE).client_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).client_plugins distclean
sub-routing-plugins-client_plugins-pro-distclean: routing\plugins\$(MAKEFILE).client_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).client_plugins distclean
sub-routing-plugins-client_plugins-pro-install_subtargets-ordered: routing\plugins\$(MAKEFILE).client_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).client_plugins install
sub-routing-plugins-client_plugins-pro-install_subtargets: routing\plugins\$(MAKEFILE).client_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).client_plugins install
sub-routing-plugins-client_plugins-pro-uninstall_subtargets-ordered: routing\plugins\$(MAKEFILE).client_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).client_plugins uninstall
sub-routing-plugins-client_plugins-pro-uninstall_subtargets: routing\plugins\$(MAKEFILE).client_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).client_plugins uninstall
routing\plugins\$(MAKEFILE).preprocessor_plugins: 
	@$(CHK_DIR_EXISTS) routing\plugins\ $(MKDIR) routing\plugins\ 
	cd routing\plugins\ && $(QMAKE) e:\svn\luckygps\routing\plugins\preprocessor_plugins.pro -o $(MAKEFILE).preprocessor_plugins
sub-routing-plugins-preprocessor_plugins-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) routing\plugins\ $(MKDIR) routing\plugins\ 
	cd routing\plugins\ && $(QMAKE) e:\svn\luckygps\routing\plugins\preprocessor_plugins.pro -o $(MAKEFILE).preprocessor_plugins
sub-routing-plugins-preprocessor_plugins-pro: routing\plugins\$(MAKEFILE).preprocessor_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins
sub-routing-plugins-preprocessor_plugins-pro-make_default-ordered: routing\plugins\$(MAKEFILE).preprocessor_plugins sub-routing-plugins-client_plugins-pro-make_default-ordered  FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins 
sub-routing-plugins-preprocessor_plugins-pro-make_default: routing\plugins\$(MAKEFILE).preprocessor_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins 
sub-routing-plugins-preprocessor_plugins-pro-make_first-ordered: routing\plugins\$(MAKEFILE).preprocessor_plugins sub-routing-plugins-client_plugins-pro-make_first-ordered  FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins first
sub-routing-plugins-preprocessor_plugins-pro-make_first: routing\plugins\$(MAKEFILE).preprocessor_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins first
sub-routing-plugins-preprocessor_plugins-pro-all-ordered: routing\plugins\$(MAKEFILE).preprocessor_plugins sub-routing-plugins-client_plugins-pro-all-ordered  FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins all
sub-routing-plugins-preprocessor_plugins-pro-all: routing\plugins\$(MAKEFILE).preprocessor_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins all
sub-routing-plugins-preprocessor_plugins-pro-clean-ordered: routing\plugins\$(MAKEFILE).preprocessor_plugins sub-routing-plugins-client_plugins-pro-clean-ordered  FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins clean
sub-routing-plugins-preprocessor_plugins-pro-clean: routing\plugins\$(MAKEFILE).preprocessor_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins clean
sub-routing-plugins-preprocessor_plugins-pro-distclean-ordered: routing\plugins\$(MAKEFILE).preprocessor_plugins sub-routing-plugins-client_plugins-pro-distclean-ordered  FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins distclean
sub-routing-plugins-preprocessor_plugins-pro-distclean: routing\plugins\$(MAKEFILE).preprocessor_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins distclean
sub-routing-plugins-preprocessor_plugins-pro-install_subtargets-ordered: routing\plugins\$(MAKEFILE).preprocessor_plugins sub-routing-plugins-client_plugins-pro-install_subtargets-ordered  FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins install
sub-routing-plugins-preprocessor_plugins-pro-install_subtargets: routing\plugins\$(MAKEFILE).preprocessor_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins install
sub-routing-plugins-preprocessor_plugins-pro-uninstall_subtargets-ordered: routing\plugins\$(MAKEFILE).preprocessor_plugins sub-routing-plugins-client_plugins-pro-uninstall_subtargets-ordered  FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins uninstall
sub-routing-plugins-preprocessor_plugins-pro-uninstall_subtargets: routing\plugins\$(MAKEFILE).preprocessor_plugins FORCE
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins uninstall
$(MAKEFILE).luckygps-client: 
	$(QMAKE) e:\svn\luckygps\luckygps-client.pro -o $(MAKEFILE).luckygps-client
sub-luckygps-client-pro-qmake_all:  FORCE
	$(QMAKE) e:\svn\luckygps\luckygps-client.pro -o $(MAKEFILE).luckygps-client
sub-luckygps-client-pro: $(MAKEFILE).luckygps-client FORCE
	$(MAKE) -f $(MAKEFILE).luckygps-client
sub-luckygps-client-pro-make_default-ordered: $(MAKEFILE).luckygps-client sub-routing-plugins-preprocessor_plugins-pro-make_default-ordered  FORCE
	$(MAKE) -f $(MAKEFILE).luckygps-client 
sub-luckygps-client-pro-make_default: $(MAKEFILE).luckygps-client FORCE
	$(MAKE) -f $(MAKEFILE).luckygps-client 
sub-luckygps-client-pro-make_first-ordered: $(MAKEFILE).luckygps-client sub-routing-plugins-preprocessor_plugins-pro-make_first-ordered  FORCE
	$(MAKE) -f $(MAKEFILE).luckygps-client first
sub-luckygps-client-pro-make_first: $(MAKEFILE).luckygps-client FORCE
	$(MAKE) -f $(MAKEFILE).luckygps-client first
sub-luckygps-client-pro-all-ordered: $(MAKEFILE).luckygps-client sub-routing-plugins-preprocessor_plugins-pro-all-ordered  FORCE
	$(MAKE) -f $(MAKEFILE).luckygps-client all
sub-luckygps-client-pro-all: $(MAKEFILE).luckygps-client FORCE
	$(MAKE) -f $(MAKEFILE).luckygps-client all
sub-luckygps-client-pro-clean-ordered: $(MAKEFILE).luckygps-client sub-routing-plugins-preprocessor_plugins-pro-clean-ordered  FORCE
	$(MAKE) -f $(MAKEFILE).luckygps-client clean
sub-luckygps-client-pro-clean: $(MAKEFILE).luckygps-client FORCE
	$(MAKE) -f $(MAKEFILE).luckygps-client clean
sub-luckygps-client-pro-distclean-ordered: $(MAKEFILE).luckygps-client sub-routing-plugins-preprocessor_plugins-pro-distclean-ordered  FORCE
	$(MAKE) -f $(MAKEFILE).luckygps-client distclean
sub-luckygps-client-pro-distclean: $(MAKEFILE).luckygps-client FORCE
	$(MAKE) -f $(MAKEFILE).luckygps-client distclean
sub-luckygps-client-pro-install_subtargets-ordered: $(MAKEFILE).luckygps-client sub-routing-plugins-preprocessor_plugins-pro-install_subtargets-ordered  FORCE
	$(MAKE) -f $(MAKEFILE).luckygps-client install
sub-luckygps-client-pro-install_subtargets: $(MAKEFILE).luckygps-client FORCE
	$(MAKE) -f $(MAKEFILE).luckygps-client install
sub-luckygps-client-pro-uninstall_subtargets-ordered: $(MAKEFILE).luckygps-client sub-routing-plugins-preprocessor_plugins-pro-uninstall_subtargets-ordered  FORCE
	$(MAKE) -f $(MAKEFILE).luckygps-client uninstall
sub-luckygps-client-pro-uninstall_subtargets: $(MAKEFILE).luckygps-client FORCE
	$(MAKE) -f $(MAKEFILE).luckygps-client uninstall

Makefile: luckygps.pro  ..\..\Qt\qt-4.7.3\mkspecs\default\qmake.conf ..\..\Qt\qt-4.7.3\mkspecs\qconfig.pri \
		..\..\Qt\qt-4.7.3\mkspecs\features\qt_functions.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\qt_config.prf \
		..\..\Qt\qt-4.7.3\mkspecs\win32-msvc2008\qmake.conf \
		..\..\Qt\qt-4.7.3\mkspecs\features\exclusive_builds.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\default_pre.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\win32\default_pre.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\debug.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\debug_and_release.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\default_post.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\win32\default_post.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\win32\rtti.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\win32\exceptions.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\win32\stl.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\shared.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\win32\embed_manifest_exe.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\win32\embed_manifest_dll.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\warn_on.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\qt.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\win32\thread.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\moc.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\win32\windows.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\resources.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\uic.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\yacc.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\lex.prf \
		..\..\Qt\qt-4.7.3\mkspecs\features\include_source_dir.prf
	$(QMAKE) -o Makefile luckygps.pro
..\..\Qt\qt-4.7.3\mkspecs\qconfig.pri:
..\..\Qt\qt-4.7.3\mkspecs\features\qt_functions.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\qt_config.prf:
..\..\Qt\qt-4.7.3\mkspecs\win32-msvc2008\qmake.conf:
..\..\Qt\qt-4.7.3\mkspecs\features\exclusive_builds.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\default_pre.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\win32\default_pre.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\debug.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\debug_and_release.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\default_post.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\win32\default_post.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\win32\rtti.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\win32\exceptions.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\win32\stl.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\shared.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\win32\embed_manifest_exe.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\win32\embed_manifest_dll.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\warn_on.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\qt.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\win32\thread.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\moc.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\win32\windows.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\resources.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\uic.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\yacc.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\lex.prf:
..\..\Qt\qt-4.7.3\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile luckygps.pro

qmake_all: sub-routing-plugins-client_plugins-pro-qmake_all sub-routing-plugins-preprocessor_plugins-pro-qmake_all sub-luckygps-client-pro-qmake_all FORCE

make_default: sub-routing-plugins-client_plugins-pro-make_default-ordered sub-routing-plugins-preprocessor_plugins-pro-make_default-ordered sub-luckygps-client-pro-make_default-ordered FORCE
make_first: sub-routing-plugins-client_plugins-pro-make_first-ordered sub-routing-plugins-preprocessor_plugins-pro-make_first-ordered sub-luckygps-client-pro-make_first-ordered FORCE
all: sub-routing-plugins-client_plugins-pro-all-ordered sub-routing-plugins-preprocessor_plugins-pro-all-ordered sub-luckygps-client-pro-all-ordered FORCE
clean: sub-routing-plugins-client_plugins-pro-clean-ordered sub-routing-plugins-preprocessor_plugins-pro-clean-ordered sub-luckygps-client-pro-clean-ordered FORCE
distclean: sub-routing-plugins-client_plugins-pro-distclean-ordered sub-routing-plugins-preprocessor_plugins-pro-distclean-ordered sub-luckygps-client-pro-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-routing-plugins-client_plugins-pro-install_subtargets-ordered sub-routing-plugins-preprocessor_plugins-pro-install_subtargets-ordered sub-luckygps-client-pro-install_subtargets-ordered FORCE
uninstall_subtargets: sub-routing-plugins-client_plugins-pro-uninstall_subtargets-ordered sub-routing-plugins-preprocessor_plugins-pro-uninstall_subtargets-ordered sub-luckygps-client-pro-uninstall_subtargets-ordered FORCE

sub-routing-plugins-client_plugins-pro-sub_Debug_ordered: routing\plugins\$(MAKEFILE).client_plugins
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).client_plugins debug
sub-routing-plugins-preprocessor_plugins-pro-sub_Debug_ordered: routing\plugins\$(MAKEFILE).preprocessor_plugins sub-routing-plugins-client_plugins-pro-sub_Debug_ordered 
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins debug
sub-luckygps-client-pro-sub_Debug_ordered: $(MAKEFILE).luckygps-client sub-routing-plugins-preprocessor_plugins-pro-sub_Debug_ordered 
	$(MAKE) -f $(MAKEFILE).luckygps-client debug
debug: sub-routing-plugins-client_plugins-pro-sub_Debug_ordered sub-routing-plugins-preprocessor_plugins-pro-sub_Debug_ordered sub-luckygps-client-pro-sub_Debug_ordered

sub-routing-plugins-client_plugins-pro-sub_Release_ordered: routing\plugins\$(MAKEFILE).client_plugins
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).client_plugins release
sub-routing-plugins-preprocessor_plugins-pro-sub_Release_ordered: routing\plugins\$(MAKEFILE).preprocessor_plugins sub-routing-plugins-client_plugins-pro-sub_Release_ordered 
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins release
sub-luckygps-client-pro-sub_Release_ordered: $(MAKEFILE).luckygps-client sub-routing-plugins-preprocessor_plugins-pro-sub_Release_ordered 
	$(MAKE) -f $(MAKEFILE).luckygps-client release
release: sub-routing-plugins-client_plugins-pro-sub_Release_ordered sub-routing-plugins-preprocessor_plugins-pro-sub_Release_ordered sub-luckygps-client-pro-sub_Release_ordered

sub-routing-plugins-client_plugins-pro-check_ordered: routing\plugins\$(MAKEFILE).client_plugins
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).client_plugins check
sub-routing-plugins-preprocessor_plugins-pro-check_ordered: routing\plugins\$(MAKEFILE).preprocessor_plugins sub-routing-plugins-client_plugins-pro-check_ordered 
	cd routing\plugins\ && $(MAKE) -f $(MAKEFILE).preprocessor_plugins check
sub-luckygps-client-pro-check_ordered: $(MAKEFILE).luckygps-client sub-routing-plugins-preprocessor_plugins-pro-check_ordered 
	$(MAKE) -f $(MAKEFILE).luckygps-client check
check: sub-routing-plugins-client_plugins-pro-check_ordered sub-routing-plugins-preprocessor_plugins-pro-check_ordered sub-luckygps-client-pro-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

