Document: luckygps
Title: Debian luckygps Manual
Author: <insert document author here>
Abstract: This manual describes what luckygps is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/luckygps/luckygps.sgml.gz

Format: postscript
Files: /usr/share/doc/luckygps/luckygps.ps.gz

Format: text
Files: /usr/share/doc/luckygps/luckygps.text.gz

Format: HTML
Index: /usr/share/doc/luckygps/html/index.html
Files: /usr/share/doc/luckygps/html/*.html
